# Generated by Django 4.1.3 on 2022-12-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Product',
        ),
    ]
