# Generated by Django 4.1.3 on 2022-12-10 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_rename_user_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Nairobi', 'Nairobi City'), ('Mombasa', 'Mombasa City'), ('Kisumu', 'Kisumu City'), ('Nakuru', 'Nakuru City'), ('Wajir', 'Wajir Town'), ('Mandera', 'Mandera Town'), ('Marsabit', 'Marsabit Town'), ('Isiolo', 'Isiolo Town'), ('Meru', 'Meru Town'), ('Tharaka-Nithi', 'Kathwana Town'), ('Embu', 'Embu Town'), ('Kitui', 'Kitui Town'), ('Machakos', 'Machakos Town'), ('Makueni', 'Wote Town'), ('Nyandarua', 'Ol Kalou Town'), ('Nyeri', 'Nyeri Town'), ('Kirinyaga', 'Kerugoya Town'), ('Muranga', 'Muranga Town'), ('Kiambu', 'Kiambu Town'), ('Turkana', 'Lodway Town'), ('West Pokot', 'Kapenguria Town'), ('Samburu', 'Maralal Town'), ('Trans-Nzoia', ' Kitale Town'), ('Uasin Gishu', 'Eldoret Town'), ('Elgeyo-Marakwet', 'Iten'), ('Nandi', 'Kapsabet Town'), ('Baringo', 'Kabarnet Town'), ('Laikipia', 'Nanyuki Town'), ('Narok', 'Narok Town'), ('Kajiado', 'Kajiado Town'), ('Kericho', 'Kericho Town'), ('Bomet', 'Bomet Town'), ('Kakamega', 'Kakamega Town'), ('Vihiga', 'Mbale'), ('Bungoma', 'Bungoma Town'), ('Busia', 'Busia Town'), ('Siaya', 'Siaya Town'), ('Homa Bay', 'Homa Bay Town'), ('Migori', 'Migori Town'), ('Kisii', 'Kisii Town'), ('kilifi', 'kilifi Town'), ('Nyamira', 'Nyamira Town'), ('Kwale', 'Kwale Town'), ('Tana River', 'Hola'), ('Lamu', 'Lamu Town'), ('Taita-Taveta', 'Mwatete Town'), ('Garissa', 'Garissa Town')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
