# Generated by Django 4.1.3 on 2023-01-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_customer_locality_remove_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
    ]
