# Generated by Django 4.1.3 on 2023-10-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_maincategory_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincategory',
            name='parent',
        ),
    ]
